In [2]:
from pandas import *

In [3]:
training_set = read_csv('/opt/personal/datasets/BlackFriday.csv')
training_set.head()

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969

In [6]:
male = training_set[training_set.Gender == 'M']
female = training_set[training_set.Gender == 'F']

In [7]:
male, female

(        User_ID Product_ID Gender    Age  Occupation City_Category  \
 4       1000002  P00285442      M    55+          16             C
 5       1000003  P00193542      M  26-35          15             A
 6       1000004  P00184942      M  46-50           7             B
 7       1000004  P00346142      M  46-50           7             B
 8       1000004   P0097242      M  46-50           7             B
 9       1000005  P00274942      M  26-35          20             A
 10      1000005  P00251242      M  26-35          20             A
 11      1000005  P00014542      M  26-35          20             A
 12      1000005  P00031342      M  26-35          20             A
 13      1000005  P00145042      M  26-35          20             A
 18      1000007  P00036842      M  36-45           1             B
 19      1000008  P00249542      M  26-35          12             C
 20      1000008  P00220442      M  26-35          12             C
 21      1000008  P00156442      M  26-35          12             C
 22      1000008  P00213742      M  26-35          12             C
 23      1000008  P00214442      M  26-35          12             C
 24      1000008  P00303442      M  26-35          12             C
 25      1000009  P00135742      M  26-35          17             C
 26      1000009  P00039942      M  26-35          17             C
 27      1000009  P00161442      M  26-35          17             C
 28      1000009  P00078742      M  26-35          17             C
 50      1000012  P00304242      M  26-35          12             C
 51      1000012  P00365242      M  26-35          12             C
 52      1000013  P00129542      M  46-50           1             C
 53      1000013  P00140742      M  46-50           1             C
 54      1000013  P00182342      M  46-50           1             C
 55      1000014  P00276642      M  36-45           0             C
 56      1000015  P00334242      M  26-35           7             A
 57      1000015  P00247542      M  26-35           7             A
 58      1000015  P00338442      M  26-35           7             A
 ...         ...        ...    ...    ...         ...           ...
 537547  1004733  P00244042      M  18-25          18             C
 537548  1004734  P00111042      M  51-55           1             B
 537549  1004734  P00345842      M  51-55           1             B
 537550  1004735  P00278242      M  46-50           3             C
 537551  1004735  P00313442      M  46-50           3             C
 537552  1004735   P0098642      M  46-50           3             C
 537553  1004735  P00119342      M  46-50           3             C
 537554  1004735  P00114042      M  46-50           3             C
 537555  1004735  P00135142      M  46-50           3             C
 537556  1004736  P00194542      M  18-25          20             A
 537557  1004736  P00175242      M  18-25          20             A
 537558  1004736  P00101942      M  18-25          20             A
 537559  1004736  P00109142      M  18-25          20             A
 537560  1004736  P00084842      M  18-25          20             A
 537561  1004736  P00078142      M  18-25          20             A
 537562  1004736  P00146742      M  18-25          20             A
 537563  1004736  P00154642      M  18-25          20             A
 537564  1004736  P00117442      M  18-25          20             A
 537565  1004736  P00051142      M  18-25          20             A
 537566  1004736  P00048742      M  18-25          20             A
 537567  1004736  P00157542      M  18-25          20             A
 537568  1004736  P00250642      M  18-25          20             A
 537569  1004736  P00023142      M  18-25          20             A
 537570  1004736  P00162442      M  18-25          20             A
 537571  1004737  P00221442      M  36-45          16             C
 537572  1004737  P00193542      M  36-45          16             C
 537573  1004737  P00111142      M  36-45          16             C
 537574  1004737  P00345942      M  36-45          16             C
 537575  1004737  P00285842      M  36-45          16             C
 537576  1004737  P00118242      M  36-45          16             C

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
 4                              4+               0                   8
 5                               3               0                   1
 6                               2               1                   1
 7                               2               1                   1
 8                               2               1                   1
 9                               1               1                   8
 10                              1               1                   5
 11                              1               1                   8
 12                              1               1                   8
 13                              1               1                   1
 18                              1               1                   1
 19                             4+               1                   1
 20                             4+               1                   5
 21                             4+               1                   8
 22                             4+               1                   8
 23                             4+               1                   8
 24                             4+               1                   1
 25                              0               0                   6
 26                              0               0                   8
 27                              0               0                   5
 28                              0               0                   5
 50                              2               0                   1
 51                              2               0                   5
 52                              3               1                   8
 53                              3               1                   1
 54                              3               1                   1
 55                              0               0                   8
 56                              1               0                   1
 57                              1               0                   8
 58                              1               0                   1
 ...                           ...             ...                 ...
 537547                          1               0                   1
 537548                          1               1                  15
 537549                          1               1                   2
 537550                          3               0                   1
 537551                          3               0                   5
 537552                          3               0                   6
 537553                          3               0                  10
 537554                          3               0                   5
 537555                          3               0                  13
 537556                          1               1                   8
 537557                          1               1                   2
 537558                          1               1                   8
 537559                          1               1                   8
 537560                          1               1                   8
 537561                          1               1                   8
 537562                          1               1                   1
 537563                          1               1                   8
 537564                          1               1                   5
 537565                          1               1                   8
 537566                          1               1                   5
 537567                          1               1                   8
 537568                          1               1                  11
 537569                          1               1                   5
 537570                          1               1                   1
 537571                          1               0                   1
 537572                          1               0                   1
 537573                          1               0                   1
 537574                          1               0                   8
 537575                          1               0                   5
 537576                          1               0                   5

         Product_Category_2  Product_Category_3  Purchase
 4                      NaN                 NaN      7969
 5                      2.0                 NaN     15227
 6                      8.0                17.0     19215
 7                     15.0                 NaN     15854
 8                     16.0                 NaN     15686
 9                      NaN                 NaN      7871
 10                    11.0                 NaN      5254
 11                     NaN                 NaN      3957
 12                     NaN                 NaN      6073
 13                     2.0                 5.0     15665
 18                    14.0                16.0     11788
 19                     5.0                15.0     19614
 20                    14.0                 NaN      8584
 21                     NaN                 NaN      9872
 22                     NaN                 NaN      9743
 23                     NaN                 NaN      5982
 24                     8.0                14.0     11927
 25                     8.0                 NaN     16662
 26                     NaN                 NaN      5887
 27                    14.0                 NaN      6973
 28                     8.0                14.0      5391
 50                     6.0                 NaN     15246
 51                     8.0                 NaN      6865
 52                    14.0                 NaN      5839
 53                    15.0                 NaN     15912
 54                     5.0                 6.0     12107
 55                    11.0                 NaN      5848
 56                     8.0                 NaN     19653
 57                    16.0                 NaN      5958
 58                    16.0                 NaN     11415
 ...                    ...                 ...       ...
 537547                 2.0                15.0     11543
 537548                 NaN                 NaN     20924
 537549                 8.0                14.0     13082
 537550                 NaN                 NaN     11658
 537551                 6.0                 8.0      6863
 537552                 8.0                 NaN     16415
 537553                13.0                 NaN     18526
 537554                14.0                 NaN      7099
 537555                16.0                 NaN       578
 537556                14.0                 NaN      2183
 537557                 NaN                 NaN     12724
 537558                17.0                 NaN      7796
 537559                17.0                 NaN      7770
 537560                16.0                 NaN      5940
 537561                16.0                 NaN      7834
 537562                13.0                14.0     11508
 537563                 NaN                 NaN      6074
 537564                14.0                 NaN      7084
 537565                 NaN                 NaN      7934
 537566                 NaN                 NaN      5350
 537567                14.0                 NaN      1994
 537568                 NaN                 NaN      5930
 537569                14.0                 NaN      7042
 537570                16.0                 NaN     15491
 537571                 2.0                 5.0     11852
 537572                 2.0                 NaN     11664
 537573                15.0                16.0     19196
 537574                15.0                 NaN      8043
 537575                 NaN                 NaN      7172
 537576                 8.0                 NaN      6875

 [405380 rows x 12 columns],
         User_ID Product_ID Gender    Age  Occupation City_Category  \
 0       1000001  P00069042      F   0-17          10             A
 1       1000001  P00248942      F   0-17          10             A
 2       1000001  P00087842      F   0-17          10             A
 3       1000001  P00085442      F   0-17          10             A
 14      1000006  P00231342      F  51-55           9             A
 15      1000006  P00190242      F  51-55           9             A
 16      1000006   P0096642      F  51-55           9             A
 17      1000006  P00058442      F  51-55           9             A
 29      1000010  P00085942      F  36-45           1             B
 30      1000010  P00118742      F  36-45           1             B
 31      1000010  P00297942      F  36-45           1             B
 32      1000010  P00266842      F  36-45           1             B
 33      1000010  P00058342      F  36-45           1             B
 34      1000010  P00032442      F  36-45           1             B
 35      1000010  P00105942      F  36-45           1             B
 36      1000010  P00182642      F  36-45           1             B
 37      1000010  P00186942      F  36-45           1             B
 38      1000010  P00155442      F  36-45           1             B
 39      1000010  P00221342      F  36-45           1             B
 40      1000010  P00087242      F  36-45           1             B
 41      1000010  P00111142      F  36-45           1             B
 42      1000010  P00259342      F  36-45           1             B
 43      1000010   P0094542      F  36-45           1             B
 44      1000010  P00148642      F  36-45           1             B
 45      1000010  P00312142      F  36-45           1             B
 46      1000010  P00113242      F  36-45           1             B
 47      1000011  P00192642      F  26-35           1             C
 48      1000011  P00110842      F  26-35           1             C
 49      1000011  P00189642      F  26-35           1             C
 65      1000016  P00244242      F  36-45           0             C
 ...         ...        ...    ...    ...         ...           ...
 537313  1004699  P00046142      F  18-25           0             C
 537314  1004699  P00216142      F  18-25           0             C
 537315  1004699  P00198742      F  18-25           0             C
 537316  1004699  P00042942      F  18-25           0             C
 537317  1004699  P00184442      F  18-25           0             C
 537338  1004705  P00031042      F  18-25           0             C
 537339  1004705  P00085242      F  18-25           0             C
 537340  1004705  P00188742      F  18-25           0             C
 537341  1004705  P00314042      F  18-25           0             C
 537342  1004705  P00042842      F  18-25           0             C
 537343  1004705  P00117842      F  18-25           0             C
 537344  1004705  P00087242      F  18-25           0             C
 537345  1004705  P00165842      F  18-25           0             C
 537346  1004705  P00348242      F  18-25           0             C
 537404  1004719  P00070042      F  36-45           9             C
 537462  1004726  P00069042      F  36-45          16             C
 537463  1004726  P00148642      F  36-45          16             C
 537464  1004726  P00058042      F  36-45          16             C
 537465  1004726  P00216342      F  36-45          16             C
 537466  1004726  P00024342      F  36-45          16             C
 537467  1004726  P00036842      F  36-45          16             C
 537468  1004726  P00302642      F  36-45          16             C
 537469  1004726  P00296042      F  36-45          16             C
 537470  1004726  P00132042      F  36-45          16             C
 537471  1004726  P00034842      F  36-45          16             C
 537472  1004726  P00037142      F  36-45          16             C
 537473  1004726  P00058442      F  36-45          16             C
 537474  1004726  P00303242      F  36-45          16             C
 537475  1004727  P00295942      F    55+           0             C
 537476  1004727  P00351142      F    55+           0             C

        Stay_In_Current_City_Years  Marital_Status  Product_Category_1  \
 0                               2               0                   3
 1                               2               0                   1
 2                               2               0                  12
 3                               2               0                  12
 14                              1               0                   5
 15                              1               0                   4
 16                              1               0                   2
 17                              1               0                   5
 29                             4+               1                   2
 30                             4+               1                   5
 31                             4+               1                   8
 32                             4+               1                   5
 33                             4+               1                   3
 34                             4+               1                   5
 35                             4+               1                   5
 36                             4+               1                   2
 37                             4+               1                   5
 38                             4+               1                   1
 39                             4+               1                   1
 40                             4+               1                  14
 41                             4+               1                   1
 42                             4+               1                   5
 43                             4+               1                   2
 44                             4+               1                   6
 45                             4+               1                   8
 46                             4+               1                   1
 47                              1               0                   8
 48                              1               0                   1
 49                              1               0                   8
 65                              0               1                   1
 ...                           ...             ...                 ...
 537313                         4+               0                   1
 537314                         4+               0                   1
 537315                         4+               0                   1
 537316                         4+               0                   1
 537317                         4+               0                   1
 537338                          0               1                   8
 537339                          0               1                   8
 537340                          0               1                   8
 537341                          0               1                  14
 537342                          0               1                   5
 537343                          0               1                   5
 537344                          0               1                  14
 537345                          0               1                  14
 537346                          0               1                   8
 537404                         4+               0                   1
 537462                          2               1                   3
 537463                          2               1                   6